# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'atualizar_livro.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(900, 550)
        self.pushButton_alterar = QtWidgets.QPushButton(Dialog)
        self.pushButton_alterar.setGeometry(QtCore.QRect(340, 490, 80, 25))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("PiltoverLibrary/Icon/checked.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("Icon/checked.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_alterar.setIcon(icon)
        self.pushButton_alterar.setObjectName("pushButton_alterar")
        self.lineEdit_ISBN = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ISBN.setGeometry(QtCore.QRect(336, 211, 290, 25))
        self.lineEdit_ISBN.setObjectName("lineEdit_ISBN")
        self.pushButton_cancelar = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancelar.setEnabled(True)
        self.pushButton_cancelar.setGeometry(QtCore.QRect(450, 490, 80, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_cancelar.sizePolicy().hasHeightForWidth())
        self.pushButton_cancelar.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("PiltoverLibrary/Icon/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap("Icon/cancel.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_cancelar.setIcon(icon1)
        self.pushButton_cancelar.setObjectName("pushButton_cancelar")
        self.label_editora = QtWidgets.QLabel(Dialog)
        self.label_editora.setGeometry(QtCore.QRect(336, 134, 290, 17))
        self.label_editora.setObjectName("label_editora")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(336, 407, 290, 17))
        self.label_7.setObjectName("label_7")
        self.lineEdit_ano = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ano.setGeometry(QtCore.QRect(336, 268, 290, 25))
        self.lineEdit_ano.setObjectName("lineEdit_ano")
        self.lineEdit_titulo = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_titulo.setGeometry(QtCore.QRect(336, 103, 290, 25))
        self.lineEdit_titulo.setObjectName("lineEdit_titulo")
        self.lineEdit_editora = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_editora.setGeometry(QtCore.QRect(336, 157, 290, 25))
        self.lineEdit_editora.setObjectName("lineEdit_editora")
        self.lineEdit_Genero = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_Genero.setGeometry(QtCore.QRect(336, 322, 290, 25))
        self.lineEdit_Genero.setObjectName("lineEdit_Genero")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(336, 21, 290, 38))
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(336, 299, 290, 17))
        self.label_5.setObjectName("label_5")
        self.lineEdit_descricao = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_descricao.setGeometry(QtCore.QRect(336, 376, 290, 25))
        self.lineEdit_descricao.setObjectName("lineEdit_descricao")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(336, 188, 290, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit_autor = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_autor.setGeometry(QtCore.QRect(336, 430, 290, 25))
        self.lineEdit_autor.setObjectName("lineEdit_autor")
        self.label_titulo = QtWidgets.QLabel(Dialog)
        self.label_titulo.setGeometry(QtCore.QRect(336, 80, 290, 17))
        self.label_titulo.setObjectName("label_titulo")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(336, 353, 290, 17))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(336, 242, 290, 20))
        self.label_4.setObjectName("label_4")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(40, 0, 290, 128))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border: None;\n"
"}")
        self.pushButton_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("PiltoverLibrary/Icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap("Icon/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_3.setIcon(icon2)
        self.pushButton_3.setIconSize(QtCore.QSize(128, 128))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_Excluir = QtWidgets.QPushButton(Dialog)
        self.pushButton_Excluir.setGeometry(QtCore.QRect(550, 490, 80, 25))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("PiltoverLibrary/Icon/garbage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap("Icon/garbage.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pushButton_Excluir.setIcon(icon3)
        self.pushButton_Excluir.setObjectName("pushButton_Excluir")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_alterar.setText(_translate("Dialog", "Confirmar"))
        self.pushButton_cancelar.setText(_translate("Dialog", "Cancelar"))
        self.label_editora.setText(_translate("Dialog", "Editora"))
        self.label_7.setText(_translate("Dialog", "Autor"))
        self.label.setText(_translate("Dialog", "Editar livro"))
        self.label_5.setText(_translate("Dialog", "Gênero"))
        self.label_2.setText(_translate("Dialog", "ISBN"))
        self.label_titulo.setText(_translate("Dialog", "Título"))
        self.label_6.setText(_translate("Dialog", "Descrição"))
        self.label_4.setText(_translate("Dialog", "Ano"))
        self.pushButton_Excluir.setText(_translate("Dialog", "Excluir"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

